version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=accounting_manager
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql
    command: >
      sh -c "
             echo 'Waiting for MySQL to be ready...'
             while ! nc -z mysql 3306; do
               sleep 1
             done
             echo 'MySQL is ready!'
             php artisan key:generate &&
             php artisan migrate --seed --force &&
             php artisan octane:start --server=swoole --host=0.0.0.0"

  mysql:
    image: mariadb:10.5
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=accounting_manager
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  nginx-logs:
    driver: local