version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=accounting_manager
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 192M
        reservations:
          memory: 128M
    command: >
      sh -c "
             echo 'Waiting for MySQL to be ready...'
             while ! nc -z mysql 3306; do
               sleep 1
             done
             echo 'MySQL is ready!'
             php artisan key:generate &&
             php artisan migrate --seed --force &&
             php artisan octane:start --server=swoole --host=0.0.0.0 --workers=1 --task-workers=1"

  mysql:
    image: mariadb:10.5
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=accounting_manager
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    command: >
      --innodb-buffer-pool-size=32M
      --innodb-log-buffer-size=2M
      --innodb-log-file-size=8M
      --max-connections=10
      --key-buffer-size=8M
      --sort-buffer-size=512K
      --read-buffer-size=256K
      --read-rnd-buffer-size=512K
      --thread-cache-size=8
      --query-cache-size=4M
      --query-cache-limit=256K
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  nginx-logs:
    driver: local