services:
  accounting_manager:
    container_name: accounting_manager
    image: ghcr.io/carandev/accounting-manager:v2025.09.28-2ce5d92-v4
    restart: unless-stopped
    ports:
      - "6686:6686"
    environment:
      APP_NAME: Accounting Manager
      APP_ENV: production
      APP_DEBUG: true
      APP_URL: https://accounting-manager.carandev.me
      APP_LOCALE: es
      ASSET_URL: https://accounting-manager.carandev.me
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3123
      DB_DATABASE: accounting_manager_db
      DB_USERNAME: root
      DB_PASSWORD: IAjF^iRi2aZb$5
    volumes:
      - ./noton-data/uploads:/srv/www/storage/app/public
